name: tracker_admin
description: "Tracker Admin."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  json_annotation: ^4.8.1
  build_runner: ^2.4.6
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  go_router: ^10.1.2
  firebase_database: ^10.3.8
  fluttertoast: ^8.2.4
  intl: ^0.19.0
  permission_handler: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
